tap "exolnet/deprecated"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "phinze/cask"

brew "autoconf"
brew "openldap"
brew "flow"
brew "libtool"
brew "libpng"
brew "gcc"
brew "gdb"
brew "git"
brew "python"
brew "httpd", restart_service: true
brew "hugo"
brew "libusb"
brew "ios-webkit-debug-proxy"
brew "libiconv"
brew "mariadb", restart_service: true
brew "minikube"
brew "node", link: false
brew "pkg-config"
brew "watchman"
brew "wget"
brew "yarn"
brew "zlib"
brew "zsh"
brew "heroku/brew/heroku"

cask "android-sdk"
cask "java8"
cask "vagrant"
cask "virtualbox"
